### ISSUE TITLE
Is it still being maintained?

### ISSUE THREAD

**Issue by randy3k** [jcoc611/sublime-websocket-client#1]
How about moving it to https://github.com/packagecontrol?

**Comment by jcoc611** [comment]
Not actively maintained. I think it would be a great idea to move it. What are the steps?

**Comment by FichteFoll** [comment]
I believe you should be able to transfer it to `packagecontrol` in the repo's settings, after which I'll add you as a collaborator and @randy3k will already have access to the repo, just like all the others there. If you are not, you can either transfer it to me or I add you to the org first.

**Comment by jcoc611** [comment]
> I believe you should be able to transfer it to `packagecontrol` in the repo's settings, after which I'll add you as a collaborator and @randy3k will already have access to the repo, just like all the others there. If you are not, you can either transfer it to me or I add you to the org first.

Oh yes, could you add me to the org? I will transfer it to `packagecontrol` afterwards. Thanks!

Alternatively, if that's too much work, I can just transfer it to you.

**Comment by jcoc611** [comment]
@FichteFoll Transferred now

**Comment by FichteFoll** [comment]
I invited you into the org. You should be able to move to it after accepting and … as I was typing, it appears you already did.

Just as a clarification, you'll keep admin rights over the repo as its original creator, but a handful of maintainers will also be able to update it.

**Comment by jcoc611** [comment]
@FichteFoll by the way, is there interest in moving this one as well? https://github.com/jcoc611/sublime-six

**Comment by FichteFoll** [comment]
Sure, if you don't want to maintain it anymore, having a few people with commit access is always good to have in case an update is needed.

I'll update the URL in package_control_channel later.
